### ISSUE TITLE
Virus detected in file orig_file.exe

### ISSUE THREAD

**Issue by jamesbgit** [vikwin/pcapfex#1]
When I downloaded the code, my anti-virus program detected a virus in the file orig_file.exe which is in the folder pcapfex-master\tests\scenarios\4.6.

The antivirus report was:
Event: Risk Found!
Security risk detected: Trojan.ADH.SMH
File: pcapfex\pcapfex-master\tests\scenarios\4.6\orig_file.exe
Location: pcapfex\pcapfex-master\tests\scenarios\4.6

**Comment by arces** [comment]
Tested on virus total: https://www.virustotal.com/en/file/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855/analysis/1468874873/ 
Even if it is malicious you shouldn't have to run it.

**Comment by jamesbgit** [comment]
Did you notice the comment at the bottom of the virus total analysis?

Empty file! This file is 0 bytes in size, software running in your computer may have blocked the file that you intended to upload or you may have sent an empty file.
